repos:

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
    - id: isort

- repo: https://github.com/ambv/black
  rev: 19.3b0
  hooks:
    - id: black
      args: [--line-length=100, --target-version=py37]

- repo: https://github.com/prettier/prettier
  rev: '1.18.2' # Use the sha or tag you want to point at
  hooks:
    - id: prettier
      args: [--config=client/.prettierrc.yaml]
      files: '^.*\.tsx?$'

- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: debug-statements
    - id: flake8
      additional_dependencies: [
        'flake8-blind-except',
        'flake8-comprehensions',
        'flake8-pep3101',
        'flake8-tidy-imports',
      ]
